# Site settings
title: Nanoriot
description: Home
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nathan Foote
user_description: I am an ambitious software developer currently studying computer science at Georgia Institute of Technology. I love learning new technologies and creating new things to make life more interesting. My experience involves work with database creation and management, full stack web development, mobile development on android and desktop application development.
user_title: Software Developer
email: nfoote.alt@gmail.com
twitter_username: realNanoriot
github_username:  Nanoriot
gplus_username:  nfootegt

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
